ASPNETPayPal/Controllers/SinglePaymentsController.cs
using ASPNETPayPal.Services;
using System.Web.Mvc;

namespace ASPNETPayPal.Controllers
{
    public class SinglePaymentsController : Controller
    {
        // GET: SinglePayments
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreatePayment()
        {
            var baseUrl = Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/') + "/";
            var payment = PayPalPaymentService.CreatePayment(baseUrl, "sale");

            return Redirect(payment.GetApprovalUrl());
        }

        public ActionResult PaymentCancelled()
        {
            return RedirectToAction("Error");
        }

        public ActionResult PaymentSuccessful(string paymentId, string token, string payerId)
        {
            var payment = PayPalPaymentService.ExecutePayment(paymentId, payerId);

            return View();
        }

        public ActionResult PaymentAuthorized()
        {
            return View();
        }
    }
}

ASPNETPayPal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET PayPal Application</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>

ASPNETPayPal/Views/SinglePayments/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="page-header">
        <h3 class="text-center">ASP.NET PayPal Integration</h3>
    </div>
    <div>
        <h4>Choose a payment</h4>
        <br />
        @using (Html.BeginForm("CreatePayment", "SinglePayments", FormMethod.Post))
        {
            <button type="submit" class="btn btn-primary">Single Payment</button>
        }
    </div>
</div>